### ISSUE TITLE
existing VPC and ECS cluster

### ISSUE THREAD

**Issue by dinnouti** [adamjkeller/ecsworkshop-efsdemo#3]
The CDK code (app.py) looks for an existing VPC and ECS cluster, but starting from a fresh AWS account. Is there a recommendation or line of code showing how this previous VPC and ECS was set up?

```yaml
        ## Importing existing VPC and ECS Cluster ##
        self.vpc = ec2.Vpc.from_lookup(
            self, "VPC",
            vpc_name='{}-base/BaseVPC'.format(self.environment_name)
        )
```

**Comment by adamjkeller** [comment]
Hey there! If you are not coming to this repo from ecsworkshop.com, then I recommend to follow the README.md, which will guide you to walk through step_1 directory first, which is where you'll deploy the vpc and ecs cluster, rather than trying to import them.

https://github.com/adamjkeller/ecsworkshop-efsdemo/blob/master/step_1/app.py#L20

**Comment by adamjkeller** [comment]
Hopefully that answers the question, and my apologies for the super late response!
